apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rhz4vch91-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rhz4vch91-java-springboot-gitops